from typing import Protocol
from uuid import UUID

from backend.app.models.approval import (
    ApprovalCreate, ApprovalDecision, ApprovalResponse, AuditEventResponse,
)


class MissingCaseError(Exception): ...
class MissingApprovalError(Exception): ...
class AlreadyDecidedError(Exception): ...
class SelfApprovalError(Exception): ...


class ApprovalRepository(Protocol):
    def create(self, case_id: UUID, data: ApprovalCreate, actor_id: str) -> ApprovalResponse: ...
    def decide(self, approval_id: UUID, data: ApprovalDecision, actor_id: str) -> ApprovalResponse: ...
    def list_all(self) -> list[ApprovalResponse]: ...
    def audit_events(self, limit: int = 100) -> list[AuditEventResponse]: ...
