"""create reports table

Revision ID: 70eaec27bd75
Revises: 
Create Date: 2026-09-23 17:55:35.574522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '70eaec27bd75'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=35), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=False),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_external_id'), 'reports', ['external_id'], unique=True)
    op.create_index(op.f('ix_reports_ingested_at'), 'reports', ['ingested_at'], unique=False)
    op.create_index(op.f('ix_reports_language'), 'reports', ['language'], unique=False)
    op.create_index(op.f('ix_reports_observed_at'), 'reports', ['observed_at'], unique=False)
    op.create_index(op.f('ix_reports_source_type'), 'reports', ['source_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_source_type'), table_name='reports')
    op.drop_index(op.f('ix_reports_observed_at'), table_name='reports')
    op.drop_index(op.f('ix_reports_language'), table_name='reports')
    op.drop_index(op.f('ix_reports_ingested_at'), table_name='reports')
    op.drop_index(op.f('ix_reports_external_id'), table_name='reports')
    op.drop_table('reports')
    # ### end Alembic commands ###
